version: "3.5"
services:
  calculator-api:
    build:
      context: .
      dockerfile: ./calculator-api/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - gateway-api
    links:
      - gateway-api
  gateway-api:
    build:
      context: .
      dockerfile: ./gateway-api/Dockerfile
    ports:
      - "80:80"
